# Unindo tabelas.
SELECT * FROM VENDEDORES;
SELECT * FROM VENDAS;

#Usando a coluna de uma tabela em outra
SELECT VENDAS.ID_VENDEDOR, 
       VENDEDORES.NOME_VENDEDOR, 
       VENDAS.QTD_VENDIDA
FROM VENDAS, VENDEDORES
WHERE VENDAS.ID_VENDEDOR = VENDEDORES.ID_VENDEDOR;

#Quantidade de vendas por vendedor
SELECT VENDAS.ID_VENDEDOR, 
       VENDEDORES.NOME_VENDEDOR,
       SUM(VENDAS.QTD_VENDIDA)
 FROM VENDAS, VENDEDORES
 WHERE VENDAS.ID_VENDEDOR = VENDEDORES.ID_VENDEDOR
 GROUP BY VENDAS.ID_VENDEDOR;


# Quantidade de vendas por vendedor usando o INNER JOIN
SELECT VENDAS.ID_VENDEDOR, 
       VENDEDORES.NOME_VENDEDOR, 
       SUM(VENDAS.QTD_VENDIDA)
FROM VENDAS INNER JOIN VENDEDORES
ON VENDAS.ID_VENDEDOR = VENDEDORES.ID_VENDEDOR
GROUP BY VENDAS.ID_VENDEDOR;

SELECT NOME_LIVRO FROM LIVROS;

### Livros que não foram vendidos usando o LEFT JOIN
SELECT A.NOME_LIVRO,
       B.QTD_VENDIDA
 FROM LIVROS  A LEFT JOIN VENDAS  B
 ON B.ID_LIVRO = A.ID_LIVRO
 WHERE B.QTD_VENDIDA IS NULL ;
 
 
 SELECT LIVROS.NOME_LIVRO,
        VENDAS.QTD_VENDIDA
 FROM LIVROS  FULL JOIN VENDAS 
 ON VENDAS.ID_LIVRO = LIVROS.ID_LIVRO;


SELECT LIVROS.NOME_LIVRO,
       VENDAS.QTD_VENDIDA
 FROM LIVROS, VENDAS
 WHERE VENDAS.ID_LIVRO = LIVROS.ID_LIVRO;
 
 SELECT LIVROS.NOME_LIVRO,
       VENDAS.QTD_VENDIDA
 FROM LIVROS LEFT JOIN VENDAS
 ON VENDAS.ID_LIVRO = LIVROS.ID_LIVRO;


 SELECT VENDAS.ID_PEDIDO,
		LIVROS.NOME_LIVRO,
       VENDAS.QTD_VENDIDA
 FROM LIVROS RIGHT JOIN VENDAS
 ON VENDAS.ID_LIVRO = LIVROS.ID_LIVRO;


SELECT LIVROS.NOME_LIVRO,
       SUM(VENDAS.QTD_VENDIDA)
 FROM LIVROS, VENDAS
 WHERE VENDAS.ID_LIVRO = LIVROS.ID_LIVRO
 GROUP BY LIVROS.NOME_LIVRO;
