
#Selecionando todos os campos (*) da tabela Livros
SELECT * FROM LIVROS;

#Selecionando o Nome dos Vendedores
SELECT NOME_VENDEDOR FROM VENDEDORES;

#Apelidando um Coluna
SELECT ID_LIVRO       AS 'CÓDIGO DO LIVRO',
       NOME_LIVRO     AS 'TÍTULO' FROM LIVROS;


#Filtrando 
SELECT * FROM LIVROS 
WHERE CATEGORIA = 'BIOGRAFIA';


# Usando dois filtros
SELECT * FROM LIVROS 
WHERE PREÇO < 26 AND CATEGORIA = 'ROMANCE' ;

SELECT * FROM LIVROS 
WHERE CATEGORIA = 'ROMANCE' AND NOT(AUTORIA = 'Machado de Assis' OR AUTORIA = 'Aluísio de Azevedo') ;

#Seleção distinta
SELECT DISTINCT ID_LIVRO FROM VENDAS;

# Seleção distinta ordenada
SELECT DISTINCT ID_LIVRO FROM VENDAS 
WHERE ID_VENDEDOR = 1 
ORDER BY ID_LIVRO;

#Seleção agrupada de livros mais vendidos
SELECT ID_LIVRO, SUM(QTD_VENDIDA) FROM VENDAS
 WHERE ID_VENDEDOR = 1
 GROUP BY ID_LIVRO
 ORDER BY SUM(QTD_VENDIDA) DESC ;
 
SELECT LIVROS.NOME_LIVRO, 
       VENDAS.ID_LIVRO
FROM VENDAS, LIVROS
WHERE VENDAS.ID_VENDEDOR = 1
AND VENDAS.ID_LIVRO = LIVROS.ID_LIVRO ;


#######    Código Extra  ###############
#Filtrando com datas
SELECT * FROM VENDAS WHERE DATA_PEDIDO >= '2020-07-03';
SELECT * FROM VENDAS WHERE YEAR(DATA_PEDIDO) >= 2021;
